apiVersion: apps/v1
kind: Deployment
metadata:
  name:  destination
  labels:
    run:  destination
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      run:  destination
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run:  destination
    spec:
      containers:
      - image:  beetravels/destination-v1:node-50d8ef540932c4a925982ba50a7d8f81434e3592
        imagePullPolicy: Always
        name:  destination
        env:
          - name: PORT
            value: "9001"
          - name: HOST_IP
            value: destination
          - name: SCHEME
            value: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
      
