apiVersion: batch/v1
kind: Job
metadata:
  name: datagen-hotel
spec:
  template:
    metadata:
      name: datagen-hotel
    spec:
      containers:
        - image: beetravels/data-gen-hotel:03f717cd222cc6e0bd0327f24595b9d8e8bdc2f0
          imagePullPolicy: Always
          name: datagen-hotel
          env:
            - name: PG_USER
              value: postgress
            - name: PG_HOST
              value: bee-travels-db-postgresql
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bee-travels-db-postgresql
                  key: postgresql-password
            - name: MONGO_CONNECTION_URL
              value: mongodb://admin:admin@mongo:27017
            - name: COUCH_CONNECTION_URL
              value: http://admin:admin@couch:5984
            - name: GENERATE_DATA
              value: "false"
            - name: DATABASE
              value: postgres
      restartPolicy: OnFailure
