apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hotel
  labels:
    run:  hotel
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      run:  hotel
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run:  hotel
    spec:
      containers:
      - image:  beetravels/hotel:v0.0.1
        imagePullPolicy: Always
        name:  hotel
        env:
          - name: PORT
            value: "9002"
          - name: HOST_IP
            value: hotel
          - name: SCHEME
            value: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
      
