{{- define "bee-travels.ingress" }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bee-travels-ingress
spec:
  tls:
    - hosts: 
        - {{ .host }}
      secretName: {{ .secret }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .name}}
              servicePort: 80
{{- end}}